grid_map:
    FREE_SPACE: 0
    OBSTACLE: 1
num_maps: 10
num_forms: 10
obstacle_density: 0.10
obstacle_density_to: 0.15
th_af: 30

test_settings:
    - [32, 7, 16]
    - [32, 9, 16]
    - [32, 11, 16]
    - [48, 7, 16]
    - [48, 9, 16]
    - [48, 11, 16]
    - [64, 7, 16]
    - [64, 9, 16]
    - [64, 11, 16]
    - [32, 9, 10]
    - [32, 9, 20]
    - [32, 9, 30]
    - [48, 9, 10]
    - [48, 9, 20]
    - [48, 9, 30]
    - [64, 9, 10]
    - [64, 9, 20]
    - [64, 9, 30]
test_to_settings:
    - [20, 3, 3]
test_df_settings:
    - [32, 9, 10]
    - [32, 9, 15]
    - [32, 9, 20]
    - [32, 9, 25]
    - [32, 9, 30]
    - [32, 9, 35]
    - [32, 9, 40]

mfceq_preference:
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 0.9